# Generated by Django 6.0.2 on 2026-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNEE_CHANGED', 'Assignee Changed'), ('COMMENT_ADDED', 'Comment Added'), ('DUE_DATE_CHANGED', 'Due Date Changed')], max_length=30),
        ),
    ]
