# Generated by Django 6.0.2 on 2026-06-13 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(max_length=4000, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
